# Streamlit secrets file for deployment
# Add OpenAI API key for Streamlit Cloud deployment
# OPENAI_API_KEY = "your_api_key_here"

# Note: For Streamlit Cloud, set the OPENAI_API_KEY in the app settings
# under "Secrets" in the Streamlit Cloud dashboard
